name: Multiplatform build
on: [push]
env:
  ARCH: linux/amd64,linux/arm64/v8,linux/arm/v7    
  DOCKER_TAG: catherinium/node-minimal-lab
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_API_KEY }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}


      - name: Run build
        run: docker buildx build -t $DOCKER_TAG --platform $ARCH --push .