name: Multiplatform build
on: [push]
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        run: echo ${{ secrets.DOCKERHUB_API_KEY }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
            
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build production image
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          push: true # This would be set to true in a real world deployment scenario.
          tags: catherinium/node-minimal-lab
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max